const { onRequest } = require("firebase-functions/v2/https");
const { onSchedule } = require("firebase-functions/v2/scheduler");
const { setGlobalOptions } = require("firebase-functions/v2");
const admin = require("firebase-admin");
const vision = require("@google-cloud/vision");
admin.initializeApp();setGlobalOptions({ region: "asia-southeast1" });const client = new vision.ImageAnnotatorClient();
function setCors(res){res.set("Access-Control-Allow-Origin","*");res.set("Access-Control-Allow-Methods","POST, OPTIONS");res.set("Access-Control-Allow-Headers","Content-Type, Authorization")}
function parseThaiIdCard(text){const rawText=String(text||"");const idMatch=rawText.match(/\b\d[\s-]?\d{4}[\s-]?\d{5}[\s-]?\d{2}[\s-]?\d\b/);const idCard=idMatch?idMatch[0].replace(/\D/g,""):"";const lines=rawText.split(/\n+/).map(s=>s.trim()).filter(Boolean);const fullName=lines.find(l=>/(นาย|นาง|นางสาว|เด็กชาย|เด็กหญิง)/.test(l)&&/[ก-๙]/.test(l))||"";let prefix="",firstName="",lastName="";const nm=fullName.match(/(นาย|นาง|นางสาว|เด็กชาย|เด็กหญิง)\s*([^\s]+)\s*(.*)/);if(nm){prefix=nm[1]||"";firstName=nm[2]||"";lastName=(nm[3]||"").trim()}const flat=rawText.replace(/\n/g," ");const address=lines.find(l=>/(ที่อยู่|บ้านเลขที่|หมู่|ถนน|ตำบล|แขวง|อำเภอ|เขต|จังหวัด)/.test(l))||"";const districtMatch=flat.match(/(?:เขต|อำเภอ|อ\.|แขวง|ตำบล|ต\.)\s*([ก-๙A-Za-z\s]+?)(?=\s*(จังหวัด|จ\.|รหัส|$))/);const provinceMatch=flat.match(/(?:จังหวัด|จ\.)\s*([ก-๙A-Za-z]+)|\b(กรุงเทพมหานคร|นนทบุรี|ปทุมธานี|สมุทรปราการ)\b/);return{idCard,fullName,prefix,firstName,lastName,address:address.replace(/^ที่อยู่\s*/,"").trim(),district:(districtMatch?.[1]||"").trim(),province:(provinceMatch?.[1]||provinceMatch?.[2]||"").trim(),rawText}}
exports.ocrThaiIdCardV2=onRequest({memory:"512MiB",timeoutSeconds:60,invoker:"public"},async(req,res)=>{setCors(res);if(req.method==="OPTIONS")return res.status(204).send("");try{if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});const authHeader=req.headers.authorization||"";const idToken=authHeader.startsWith("Bearer ")?authHeader.slice(7):"";if(!idToken)return res.status(401).json({error:"Missing Firebase ID token"});await admin.auth().verifyIdToken(idToken);const{imageBase64}=req.body||{};if(!imageBase64)return res.status(400).json({error:"Missing imageBase64"});const[result]=await client.textDetection({image:{content:Buffer.from(imageBase64,"base64")}});return res.json(parseThaiIdCard(result.fullTextAnnotation?.text||""))}catch(err){console.error(err);return res.status(500).json({error:err.message||"OCR failed"})}});
exports.testTelegramReminder=onRequest({invoker:"public"},async(req,res)=>{setCors(res);if(req.method==="OPTIONS")return res.status(204).send("");return res.json({ok:true,message:"Telegram reminder endpoint placeholder"})});
exports.dailyDebtReminder=onSchedule({schedule:"0 8 * * *",timeZone:"Asia/Bangkok"},async()=>{console.log("TODO: query Firestore due debts and send Email/Telegram reminders")});
